### PR TITLE
Add tenant handling to query nodes

### PR DESCRIPTION
**Pull request by VinnyQ**
h3. WHAT

Add tenant_handling to repose for query nodes and path /v2/(tenantId)/*

h3. WHY
Currently, any tenants going through repose (all except internal teams) can search, views, and retrieve metrics for any other tenants as long as they have a valid auth token.  This change will confine their query ability to be valid only for their own metrics.

h3.  HOW
set white_list and tenant_handling attributes for recipes/query.rb similar to how recipes/ingest.rb has it.

### CODE REVIEW

**Comment by VinnyQ** [comment]
@drenalin23 @ChandraAddala @shintasmith @usnavi please review when you have a chance.  Note that I'll have a different PR to add tests to cloudmetrics-system-tests to test this new behavior.

**Comment by shintasmith** [comment]
@VinnyQ , when you run kitchen test, it outputs the file, I think. Is it possible to show the output of the system-model.cfg.xml ?

**Comment by drenalin23** [comment]
fwiw I use the following kitchen commands most often.
kitchen create (builds the basic VM)
kitchen converge (tests chef convergence)
kitchen verify (runs integration tests)
kitchen destroy (clean everything up)
kitchen test (basically runs through those 4 steps above) - but does a destroy at the end
kitchen login - will log you into the VM in any of the first 4 steps

**Comment by shintasmith** [comment]
@drenalin23, @VinnyQ  let's add those kitchen commands in README, for those of us who are less kitchen-y :-)

**Comment by VinnyQ** [comment]
Kitchen and Vagrant commands added to README.md

@shintasmith Here's the system-model.cfg.xml for the query node created by kitchen:
```
<?xml version="1.0" encoding="UTF-8"?>
<system-model xmlns='http://docs.openrepose.org/repose/system-model/v2.0'>
    <repose-cluster id="blueflood-query"
    rewrite-host-header="true"
    >
        <nodes>
            <node id="127.0.0.1" hostname="127.0.0.1" http-port="9011" />
            <node id="127.0.0.2" hostname="127.0.0.2" http-port="9011" />
        </nodes>
        <filters>
            <filter name="slf4j-http-logging" />
            <filter name="header-normalization" />
            <filter name="add-header" />
            <filter name="keystone-v2" />
            <filter name="ip-identity" />
            <filter name="rate-limiting" />
            <filter name="api-validator" />
            <filter name="ip-user" />
        </filters>
        <services>
            <service name="dist-datastore" />
        </services>
        <destinations>
            <endpoint id="blueflood-query" protocol="http" hostname="localhost" port="2500" root-path="" default="true" />
        </destinations>
    </repose-cluster>
</system-model>
```

However, the important file change is actually in keystone-v2.cfg.xml, which looks like this for the query node after the changes in this PR:
```
<keystone-v2 xmlns="http://docs.openrepose.org/repose/keystone-v2/v1.0">
    <identity-service
        username="admin"
        password="password"
        uri="https://identity.api.rackspacecloud.com"
        set-groups-in-header="true"
        />

    <white-list>
        <uri-regex>/v2.0/?</uri-regex>
    </white-list>

     <cache>
        <timeouts variability="10">
            <token>600</token>
            <group>600</group>
            <endpoints>600</endpoints>
        </timeouts>
    </cache>

    <tenant-handling>
            <validate-tenant>
            <uri-extraction-regex>/v2.0/([^/]+)/.+</uri-extraction-regex>
        </validate-tenant>
    </tenant-handling>
</keystone-v2>
```

Note that it is similar to the current keystone-v2.cfg.xml on ingest node, and I have manually tested the config does role base auth and tenant-handling on a test query node.

**Comment by drenalin23** [comment]
Why is ip-user in the list?  I'm not sure why you would need to use it - but if you do then it is likely in the wrong place at the end of the list of filters...

**Comment by drenalin23** [comment]
Ah I see - it is in the .kitchen.yml file is likely why it is showing up there.

**Comment by VinnyQ** [comment]
@drenalin23 so is that ip-user filter thing something I have to fix?

**Comment by drenalin23** [comment]
No I can fix it when I make my next testing PR.

**Comment by shintasmith** [comment]
lgtm

**Pull request merged**
